export const mockProjects = [
  {
    id: "1",
    name: "Web Application",
    description: "Main customer-facing web application",
    createdAt: "3 months ago",
    toggleCount: 4,
  },
  {
    id: "2",
    name: "Mobile App",
    description: "iOS and Android mobile applications",
    createdAt: "2 months ago",
    toggleCount: 2,
  },
  {
    id: "3",
    name: "Admin Dashboard",
    description: "Internal admin dashboard",
    createdAt: "1 month ago",
    toggleCount: 1,
  },
]

export const mockFeatureToggles = [
  {
    id: "1",
    name: "new-checkout-flow",
    description: "Enable the new streamlined checkout experience",
    enabled: true,
    strategy: "gradual",
    rolloutPercentage: 25,
    createdAt: "2 days ago",
    stale: false,
    dependencies: [],
    parameters: [],
    projectId: "1",
  },
  {
    id: "2",
    name: "dark-mode",
    description: "Enable dark mode theme across the application",
    enabled: true,
    strategy: "standard",
    createdAt: "1 week ago",
    stale: false,
    dependencies: [],
    parameters: [
      {
        type: "userId",
        values: ["user-123", "user-456", "user-789"],
        operator: "IN",
      },
    ],
    projectId: "1",
  },
  {
    id: "3",
    name: "ai-recommendations",
    description: "Show AI-powered product recommendations to users",
    enabled: false,
    strategy: "targeted",
    createdAt: "3 weeks ago",
    stale: false,
    dependencies: ["new-checkout-flow"],
    parameters: [
      {
        type: "userEmail",
        values: ["@company.com"],
        operator: "ENDS_WITH",
      },
    ],
    projectId: "1",
  },
  {
    id: "4",
    name: "beta-dashboard",
    description: "New analytics dashboard with improved visualizations",
    enabled: true,
    strategy: "targeted",
    createdAt: "1 month ago",
    stale: false,
    dependencies: [],
    parameters: [
      {
        type: "userId",
        values: ["admin-1", "admin-2"],
        operator: "IN",
      },
      {
        type: "userRole",
        values: ["admin", "analyst"],
        operator: "IN",
      },
    ],
    projectId: "3",
  },
  {
    id: "5",
    name: "legacy-payment-gateway",
    description: "Use the legacy payment processing system",
    enabled: true,
    strategy: "standard",
    createdAt: "3 months ago",
    stale: true,
    dependencies: [],
    parameters: [],
    projectId: "1",
  },
  {
    id: "6",
    name: "new-user-onboarding",
    description: "Improved onboarding flow for new users with guided tour",
    enabled: false,
    strategy: "gradual",
    rolloutPercentage: 0,
    createdAt: "2 weeks ago",
    stale: false,
    dependencies: [],
    parameters: [],
    projectId: "2",
  },
  {
    id: "7",
    name: "experimental-search",
    description: "New search algorithm with better relevance",
    enabled: false,
    strategy: "gradual",
    rolloutPercentage: 10,
    createdAt: "5 days ago",
    stale: false,
    dependencies: [],
    parameters: [
      {
        type: "country",
        values: ["US", "CA", "UK"],
        operator: "IN",
      },
    ],
    projectId: "2",
  },
]

export const parameterTypes = [
  { id: "userId", name: "User ID", description: "Target specific user IDs" },
  { id: "userEmail", name: "User Email", description: "Target users with specific email addresses" },
  { id: "userRole", name: "User Role", description: "Target users with specific roles" },
  { id: "country", name: "Country", description: "Target users from specific countries" },
  { id: "device", name: "Device Type", description: "Target specific device types" },
  { id: "browser", name: "Browser", description: "Target specific browsers" },
  { id: "custom", name: "Custom Parameter", description: "Use a custom parameter for targeting" },
]

export const operators = [
  { id: "IN", name: "Is in list", description: "Value must be in the provided list" },
  { id: "NOT_IN", name: "Is not in list", description: "Value must not be in the provided list" },
  { id: "EQUALS", name: "Equals", description: "Value must exactly match" },
  { id: "NOT_EQUALS", name: "Not equals", description: "Value must not match" },
  { id: "STARTS_WITH", name: "Starts with", description: "Value must start with the provided text" },
  { id: "ENDS_WITH", name: "Ends with", description: "Value must end with the provided text" },
  { id: "CONTAINS", name: "Contains", description: "Value must contain the provided text" },
  { id: "GREATER_THAN", name: "Greater than", description: "Value must be greater than the provided number" },
  { id: "LESS_THAN", name: "Less than", description: "Value must be less than the provided number" },
]

